version: '3.8'

# CONFIGURACIÓN TEMPORAL SIN EDGE
# Usar cuando Edge causa problemas
# Para usar: docker-compose -f docker-compose-no-edge.yml up -d

services:
  selenium-hub:
    image: selenium/hub:4.15.0
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    environment:
      - SE_GRID_MAX_SESSION=12
      - SE_GRID_BROWSER_TIMEOUT=300
      - SE_GRID_SESSION_TIMEOUT=300
    networks:
      - selenium-grid

  chrome-node:
    image: selenium/node-chrome:4.15.0
    container_name: chrome-node
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=4
      - SE_NODE_MAX_SESSIONS=4
      - SE_VNC_NO_PASSWORD=1
    ports:
      - "5900:5900"  # VNC
      - "7900:7900"  # noVNC (navegador)
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - selenium-grid

  firefox-node:
    image: selenium/node-firefox:4.15.0
    container_name: firefox-node
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=4
      - SE_NODE_MAX_SESSIONS=4
      - SE_VNC_NO_PASSWORD=1
    ports:
      - "5901:5900"  # VNC
      - "7901:7900"  # noVNC (navegador)
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - selenium-grid

networks:
  selenium-grid:
    driver: bridge

# Para usar este archivo:
# docker-compose -f docker-compose-no-edge.yml up -d